{% set name = "xvega" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xvega/archive/{{ version }}.tar.gz
  sha256: 2da97810669d9a838febfc0d9149362ca1d04d0a780caab0f8ea13e6ee70265c

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - nlohmann_json
    - xproperty >=0.12.0,<0.13.0
  run:
    - {{ pin_compatible('xproperty', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xvega  # [unix]
    - test -f ${PREFIX}/include/xvega/xvega.hpp  # [unix]
    - test -f ${PREFIX}/include/xvega/grammar/marks.hpp  # [unix]
    - test -f ${PREFIX}/include/xvega/utils/random_string.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xvega/xvegaConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xvega/xvegaConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xvega\xvega.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xvega\grammar\marks.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xvega\utils\random_string.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xvegaConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xvegaConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/QuantStack/xvega
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A C++ backend for vega
  description: vega-lite visualization system for the xeus-cling kernel
  dev_url: https://github.com/QuantStack/xvega

extra:
  recipe-maintainers:
    - SylvainCorlay
    - madhur-tandon
    - JohanMabille
